### Получить всех сотрудников
GET http://localhost:8080/employes
### Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "Test",
  "departament": 1,
  "salary": 1000
}

### Создать сотрудника2
POST http://localhost:8080/employees
Content-Type: application/json

{
"firstName": "test",
"lastName": "Test",
"departament": 1,
"salary": 4000
}

### Получить сумму зарплат сотрудников
GET http://localhost:8080.employees/salary/sum

### Получить сотрудника с максимальной зарплатой
GET http://localhost:8080.employees/salary/max

### Получить сотрудника с минимальной зарплатой
GET http://localhost:8080.employees/salary/min

### Получение всех сотрудников, зпрплата которых больше средней зарплаты
GET http://localhost:8080.employees/high-salary

### Получить список сотрудников по департаменту
GET http://localhost:8080/department/{id}/employees

### Получить сумму зарплат по департаменту
GET http://localhost:8080/department/{id}/salary/sum

### Получить максимальную зарплату по департаменту
GET http://localhost:8080/department/{id}/salary/max

### Получить минимкльную зарплату по департаменту
GET http://localhost:8080/department/{id}/salary/min

### Получить сотрудников сгруппированнных по отделам
GET http://localhost:8080/department/employees